name: run JavaScript

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run_js:  
    timeout-minutes: 10080
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use Node.js 16

      - name: Print Node.js version
        run: node -v

      - name: install
        run: |
          npm install
          
      - name: run
        run: node index.js
